# Generated by Django 5.0.8 on 2024-12-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_name", models.CharField(default="WOWY", max_length=100)),
                (
                    "site_logo",
                    models.ImageField(blank=True, null=True, upload_to="site/"),
                ),
                (
                    "favicon",
                    models.ImageField(blank=True, null=True, upload_to="site/"),
                ),
                (
                    "contact_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "contact_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "stripe_public_key",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "stripe_secret_key",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "paypal_client_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "paypal_secret",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("BDT", "Bangladeshi Taka")],
                        default="BDT",
                        max_length=3,
                    ),
                ),
                ("smtp_host", models.CharField(blank=True, max_length=255, null=True)),
                ("smtp_port", models.IntegerField(blank=True, null=True)),
                ("smtp_user", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "smtp_password",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "email_from",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
            ],
        ),
    ]
