# Generated by Django 5.0.8 on 2024-12-16 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_sitesettings_privacy_last_updated_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sitesettings",
            name="stripe_public_key",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="stripe_secret_key",
        ),
    ]
