# Generated by Django 5.0.8 on 2025-01-06 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_sitesettings_stripe_public_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='currency',
            field=models.CharField(choices=[('INR', 'Indian Rupee')], default='INR', max_length=3),
        ),
    ]
