# Generated by Django 5.0.8 on 2024-12-11 08:36

import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "offer_type",
                    models.CharField(
                        choices=[
                            ("percentage", "Percentage"),
                            ("fixed", "Fixed Amount"),
                            ("buy_get", "Buy X Get Y"),
                        ],
                        default="percentage",
                        max_length=20,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Percentage or fixed amount",
                        max_digits=10,
                    ),
                ),
                (
                    "buy_quantity",
                    models.PositiveIntegerField(
                        default=1, help_text="For Buy X Get Y offers"
                    ),
                ),
                (
                    "get_quantity",
                    models.PositiveIntegerField(
                        default=0, help_text="For Buy X Get Y offers"
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "min_purchase_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "usage_limit",
                    models.PositiveIntegerField(default=0, help_text="0 for unlimited"),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="offers/"),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        blank=True, related_name="offers", to="products.product"
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
    ]
