# Generated by Django 5.0.8 on 2024-12-07 17:43

import django.db.models.deletion
import django_extensions.db.fields
import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0002_alter_category_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Product name")),
                ("description", models.TextField(help_text="Main product description")),
                (
                    "original_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("selling_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("status", models.BooleanField(default=True)),
                ("brand", models.CharField(blank=True, max_length=200, null=True)),
                ("weight", models.CharField(blank=True, max_length=40, null=True)),
                ("stock", models.IntegerField()),
                (
                    "stock_unit",
                    models.IntegerField(
                        choices=[
                            (1, "kg"),
                            (2, "gm"),
                            (3, "ltr"),
                            (4, "ml"),
                            (5, "unit"),
                        ]
                    ),
                ),
                ("quantity", models.IntegerField()),
                (
                    "quantity_unit",
                    models.IntegerField(
                        choices=[
                            (1, "kg"),
                            (2, "gm"),
                            (3, "ltr"),
                            (4, "ml"),
                            (5, "unit"),
                        ]
                    ),
                ),
                ("top_featured", models.BooleanField(default=False)),
                ("additional_details", models.TextField(blank=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="categories.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=products.models.product_image_directory_path,
                        verbose_name="Product Image",
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Image",
                "verbose_name_plural": "Product Images",
            },
        ),
    ]
